#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 0
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    enable_tabline_ft_icon = true
    escape_key_binding = 'jk'
    file_searching_tools = ['rg', 'fd --hidden --follow . /etc /home', 'ack', 'grep', 'git']
    #file_searching_tools = ['find', 'find -not -iwholename "*.git*" ']
    wildignore = "*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg"
    todo_labels = ["@fixme", "@question", "@todo", "@idea"]

    # Disable plugins
    disable_plugins = ["vim-visual-multi","gtags"]

# == Enable autocomplete layer ===============================================
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = 'lang#markdown'

[[layers]]
    name = 'lang#vim'


[[layers]]
    name = 'gtags'
    gtagslabel = 'ctags'
#a
[[layers]]
    name = 'git'
    


# == Add plugins from GitHub  ================================================
#[[custom_plugins]]
#   repo = "plugin-sevice"                      #插件地址
#   on_cmd = ["ColorHighlight", "ColorToggle"]  #延迟加载(来自dein插件管理器在dein-options查看更多
#   merged = false                              #合并选项

[[custom_plugins]]
    repo = "mbbill/undotree"
    merged =false

[[custom_plugins]]
    repo = "cespare/vim-toml"
    merged = false

[[custom_plugins]]
    repo = "mg979/vim-visual-multi"
    merged = false

